server:
  port: 8085
spring:
  application:
    name: good-web
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.250.128
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30

