server:
  port: 8087
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.250.128
    virtual-host: /leyou
    username: leyou
    password: leyou
leyou:
  sms:
    accessKeyId:  # 你自己的accessKeyId
    accessKeySecret:  # 你自己的AccessKeySecret
    signName: # 签名名称
    verifyCodeTemplate: # 模板名称

