server:
  port: 8086
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyou?serverTimezone=GMT%2B8
    username: root
    password: 123456
  rabbitmq:
    host: 192.168.250.128
    virtual-host: /leyou
    username: leyou
    password: leyou
  redis:
    host: 192.168.250.128
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 5
mybatis:
  type-aliases-package: com.leyou.domain